/../rtl/decoder.v
/../rtl/register_file.v
/../rtl/ALU.v
/../rtl/IF_stage.v
/../rtl/ID_stage.v
/../rtl/EX_stage.v
/../rtl/MEM_stage.v
/../rtl/WB_stage.v
/../rtl/control_hazard.v
/../rtl/defi.vh
/../tb/testbench.v
/../tb/DMEM.v
