all:
#	xrun register_file.v defi.vh -access +rwc
	xrun DMEM.v /../rtl/*.v defi.vh testbench.v -access +rwc -logfile log/simulation.log -errormax 0 -top register_file -work log
#	xrun  control_hazard.v  defi.vh -access +rwc -logfile log/simulation.log -errormax 0 -top register_file -work log

